<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Single's Day Sale - 11.11</title>
    <link rel="stylesheet" href="css/dashboard.css">
</head>
<body>
    <!-- Landing Page -->
    <div class="landing-page" id="landingPage">
        <div class="grid-pattern"></div>
        
        <div class="decorative-elements">
            <div class="lightning">⚡</div>
            <div class="shopping-bag">🛍️</div>
            <div class="sparkle">✨</div>
            <div class="wave">〰️</div>
            <div class="yellow-circle"></div>
        </div>

        <div class="content-container">
            <div class="text-content">
                <div class="brand-logo">
                    <img src="images/logo asha pkk uprak.png" alt="Asha PKK Uprak Logo" class="logo-image">
                    Single's Day Festive
                </div>
                <h1 class="main-title">Singles Day</h1>
                <h2 class="sale-title">11.11 Sale</h2>
                <p class="description">
                    Rayakan hari spesial dengan penawaran terbaik! Dapatkan produk fashion, kecantikan, dan elektronik dengan harga super hemat. Jangan sampai terlewat, promo terbatas hanya hari ini!
                </p>
                <div class="date">11th November 2025</div>
                <button class="cta-button" onclick="goToCatalog()">
                    🛒 Mulai Belanja Sekarang
                </button>
            </div>

            <div class="image-content">
                <div class="phone-mockup">
                    <div class="phone-screen">
                        <div class="balloons">🎈🎈</div>
                        <div class="model-image"></div>
                        <div style="color: white; font-size: 1.2rem; font-weight: bold; margin-top: 20px;">
                            💖 Special Offers 💖
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Catalog Page -->
    <div class="catalog-page" id="catalogPage">
        <div class="container">
            <header>
                <h1>✨ Katalog Produk ✨</h1>
                <p class="subtitle">Temukan produk terbaik dengan kualitas premium</p>
                <button onclick="goToLanding()" style="background: linear-gradient(45deg, #e91e63, #ff69b4); color: white; border: none; padding: 10px 20px; border-radius: 25px; margin-top: 15px; cursor: pointer;">
                    ← Kembali ke Beranda
                </button>
            </header>

            <div class="search-container">
                <div class="search-box">
                    <input type="text" class="search-input" placeholder="Cari produk favorit Anda..." id="searchInput">
                    <button class="search-btn" onclick="searchProducts()">🔍</button>
                </div>
            </div>

            <div class="category-filter">
                <button class="category-btn active" onclick="filterCategory('all')">Semua</button>
                <button class="category-btn" onclick="filterCategory('fashion')">Fashion</button>
                <button class="category-btn" onclick="filterCategory('beauty')">Kecantikan</button>
                <button class="category-btn" onclick="filterCategory('electronics')">Elektronik</button>
                <button class="category-btn" onclick="filterCategory('home')">Rumah Tangga</button>
            </div>

            <div class="products-grid" id="productsGrid">
                <!-- Products will be generated by JavaScript -->
            </div>

            <div class="contact-section">
                <h2 class="contact-title">💬 Hubungi Kami</h2>
                <p style="color: #666; margin-bottom: 30px;">
                    Ada pertanyaan? Ingin order? Hubungi kami sekarang juga!
                </p>
                <div class="contact-buttons">
                    <a href="https://wa.me/6285772150849" class="contact-btn whatsapp-btn" target="_blank">
                        📱 WhatsApp
                    </a>
                    <a href="https://www.instagram.com/taski.sweetz?igsh=eGVmcWU3aXlkNzU=" class="contact-btn instagram-btn" target="_blank">
                        📸 Instagram
                    </a>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div id="productModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <div id="modalContent"></div>
        </div>
    </div>

    <script>
        // Sample product data
        const products = [
            {
                id: 1,
                name: "Dress Pink Elegant",
                description: "Dress cantik dengan bahan premium, cocok untuk acara formal maupun casual",
                price: "Rp 299.000",
                category: "fashion",
                emoji: "👗"
            },
            {
                id: 2,
                name: "Lipstick Matte Pink",
                description: "Lipstik dengan formula tahan lama dan warna pink yang menawan",
                price: "Rp 89.000",
                category: "beauty",
                emoji: "💄"
            },
            {
                id: 3,
                name: "Smartphone Pink Edition",
                description: "Smartphone terbaru dengan warna pink eksklusif dan performa tinggi",
                price: "Rp 4.299.000",
                category: "electronics",
                emoji: "📱"
            },
            {
                id: 4,
                name: "Sepatu Sneakers Pink",
                description: "Sepatu sneakers comfortable dengan desain trendy warna pink",
                price: "Rp 449.000",
                category: "fashion",
                emoji: "👟"
            },
            {
                id: 5,
                name: "Blush On Natural Pink",
                description: "Blush on dengan warna pink natural untuk tampilan segar sepanjang hari",
                price: "Rp 65.000",
                category: "beauty",
                emoji: "🌸"
            },
            {
                id: 6,
                name: "Headphone Pink Wireless",
                description: "Headphone wireless dengan kualitas suara jernih dan desain pink yang stylish",
                price: "Rp 799.000",
                category: "electronics",
                emoji: "🎧"
            },
            {
                id: 7,
                name: "Tas Handbag Pink",
                description: "Tas handbag elegant dengan kulit sintetis berkualitas tinggi",
                price: "Rp 349.000",
                category: "fashion",
                emoji: "👜"
            },
            {
                id: 8,
                name: "Parfum Rose Garden",
                description: "Parfum dengan aroma bunga mawar yang memikat dan tahan lama",
                price: "Rp 199.000",
                category: "beauty",
                emoji: "🌹"
            },
            {
                id: 9,
                name: "Mug Set Pink",
                description: "Set mug cantik warna pink untuk minum kopi atau teh yang lebih menyenangkan",
                price: "Rp 125.000",
                category: "home",
                emoji: "☕"
            },
            {
                id: 10,
                name: "Smartwatch Pink",
                description: "Smartwatch dengan fitur lengkap dan strap pink yang fashionable",
                price: "Rp 1.299.000",
                category: "electronics",
                emoji: "⌚"
            },
            {
                id: 11,
                name: "Bedcover Set Pink",
                description: "Set bedcover lembut dengan motif pink yang membuat kamar lebih nyaman",
                price: "Rp 189.000",
                category: "home",
                emoji: "🛏️"
            },
            {
                id: 12,
                name: "Eyeshadow Palette Pink",
                description: "Palette eyeshadow dengan berbagai shade pink untuk makeup yang stunning",
                price: "Rp 159.000",
                category: "beauty",
                emoji: "👁️"
            }
        ];

        let currentCategory = 'all';
        let filteredProducts = [...products];

        // Navigate between pages
        function goToCatalog() {
            document.getElementById('landingPage').style.display = 'none';
            document.getElementById('catalogPage').style.display = 'block';
            displayProducts();
        }

        function goToLanding() {
            document.getElementById('catalogPage').style.display = 'none';
            document.getElementById('landingPage').style.display = 'block';
        }

        // Initialize products display
        function displayProducts(productsToShow = products) {
            const grid = document.getElementById('productsGrid');
            grid.innerHTML = '';

            productsToShow.forEach((product, index) => {
                const productCard = document.createElement('div');
                productCard.className = 'product-card';
                productCard.style.animationDelay = `${index * 0.1}s`;
                
                productCard.innerHTML = `
                    <div class="product-image">
                        ${product.emoji}
                    </div>
                    <div class="product-info">
                        <h3 class="product-name">${product.name}</h3>
                        <p class="product-description">${product.description}</p>
                        <div class="product-price">${product.price}</div>
                        <div class="product-buttons">
                            <button class="btn btn-primary" onclick="showProductDetail(${product.id})">Detail</button>
                            <button class="btn btn-secondary" onclick="addToCart(${product.id})">Tambah</button>
                        </div>
                    </div>
                `;

                grid.appendChild(productCard);
            });

            // Add animation class
            setTimeout(() => {
                document.querySelectorAll('.product-card').forEach(card => {
                    card.style.animation = 'none';
                });
            }, 1000);
        }

        // Filter by category
        function filterCategory(category) {
            // Update active button
            document.querySelectorAll('.category-btn').forEach(btn => {
                btn.classList.remove('active');
            });
            event.target.classList.add('active');

            currentCategory = category;
            
            if (category === 'all') {
                filteredProducts = [...products];
            } else {
                filteredProducts = products.filter(product => product.category === category);
            }
            
            displayProducts(filteredProducts);
        }

        // Search products
        function searchProducts() {
            const searchTerm = document.getElementById('searchInput').value.toLowerCase();
            
            let searchResults = filteredProducts.filter(product => 
                product.name.toLowerCase().includes(searchTerm) || 
                product.description.toLowerCase().includes(searchTerm)
            );
            
            displayProducts(searchResults);
        }

        // Real-time search
        document.getElementById('searchInput').addEventListener('input', searchProducts);

        // Show product detail
        function showProductDetail(productId) {
            const product = products.find(p => p.id === productId);
            const modal = document.getElementById('productModal');
            const modalContent = document.getElementById('modalContent');
            
            modalContent.innerHTML = `
                <h2 style="color: #e91e63; margin-bottom: 20px;">${product.name}</h2>
                <div style="font-size: 4rem; text-align: center; margin: 20px 0;">${product.emoji}</div>
                <p style="margin-bottom: 15px; line-height: 1.6;">${product.description}</p>
                <div style="font-size: 1.5rem; font-weight: bold; color: #e91e63; margin: 20px 0;">${product.price}</div>
                <div style="display: flex; gap: 10px; margin-top: 30px;">
                    <button class="btn btn-primary" style="flex: 1;" onclick="orderProduct(${product.id})">Pesan Sekarang</button>
                    <button class="btn btn-secondary" style="flex: 1;" onclick="closeModal()">Tutup</button>
                </div>
            `;
            
            modal.style.display = 'block';
        }

        // Add to cart
        function addToCart(productId) {
            const product = products.find(p => p.id === productId);
            alert(`✅ ${product.name} berhasil ditambahkan ke keranjang!`);
        }

        // Order product
        function orderProduct(productId) {
            const product = products.find(p => p.id === productId);
            const message = `Halo! Saya tertarik dengan produk ${product.name} (${product.price}). Bisa info lebih lanjut?`;
            const whatsappUrl = `https://wa.me/6285772150849?text=${encodeURIComponent(message)}`;
            window.open(whatsappUrl, '_blank');
            closeModal();
        }

        // Close modal
        function closeModal() {
            document.getElementById('productModal').style.display = 'none';
        }

        // Modal event listeners
        document.querySelector('.close').addEventListener('click', closeModal);
        document.getElementById('productModal').addEventListener('click', function(e) {
            if (e.target === this) {
                closeModal();
            }
        });

        // Close modal with Escape key
        document.addEventListener('keydown', function(e) {
            if (e.key === 'Escape') {
                closeModal();
            }
        });

        // Initialize the page
        document.addEventListener('DOMContentLoaded', function() {
            // Add some interactive effects
            document.addEventListener('click', function(e) {
                if (e.target.closest('.product-card')) {
                    const card = e.target.closest('.product-card');
                    card.style.transform = 'translateY(-10px) scale(1.02)';
                    setTimeout(() => {
                        card.style.transform = 'translateY(0) scale(1)';
                    }, 200);
                }
            });
        });

        // Add floating animation to header
        setInterval(() => {
            const header = document.querySelector('h1');
            if (header) {
                header.style.transform = 'translateY(-2px)';
                setTimeout(() => {
                    header.style.transform = 'translateY(0px)';
                }, 1000);
            }
        }, 3000);
    </script>
</body>
</html>